### ISSUE TITLE
Complex type

### ISSUE THREAD

**Issue by meritlouka** [piotrooo/wsdl-creator#38]
Hello,
I am trying to generate wsdl for a method which rteturn complex type
so i added this line 
  * @return wrapper $WSAccount @className=App\Services\WSAccount @elementName=WSAccount

as if  i added this @className=WSAccount 
it told me that WSAccount this class not found

but now after adding namespace it generates it and give element name App\Services\WSAccount

Please I need any help in this am i do some thing wrong ?

**Comment by piotrooo** [comment]
Try to use a new annotations.
