### ISSUE TITLE
return std object 

### ISSUE THREAD

**Issue by meritlouka** [piotrooo/wsdl-creator#39]
hello sir,
congratulation on the amazing work 
i had a question please 
can i return the output to be like that 
 object(stdClass)#2 (3) { ["id"]=> int(1127) ["accountNumber"]=> string(5) "10995" ["lastModification"]=> string(19) "2017-07-02 11:42:59" }

i mean std object instead of json
thank you so much i do really appreciate any help in this

**Comment by piotrooo** [comment]
Hello,
you can return an object using a `@WebResult` annotation.

```
/**
 * @WebMethod
 * @WebResult(param="object $result { int $id string $accountNumber string $lastModification }")
 */
public function methodName()
{
    $object = new \stdClass();
    $object->id = 1127;
    $object->accountNumber = '10995';
    $object->lastModification = '2017-07-02 11:42:59';
    return $object;
}
```
