### ISSUE TITLE
soap:header support

### ISSUE THREAD

**Issue by pelex** [piotrooo/wsdl-creator#4]
Is it possible to define soap:header in WSDL file as required?

**Comment by PaulHendriks** [comment]
Has this feature been implemented yet?
I'd be great if i could include a soap:header in my generated WSDL :)

**Comment by dandrits** [comment]
hello to all @piotrooo really cool lib, does anyone else got to work this library with soap headers?

**Comment by dandrits** [comment]
bump @piotrooo maybe can you answer the question above?

**Comment by pelex** [comment]
@dandrits Here is an example how to i used headers in my webservices. This example works with c# webservice client. It's only example and it's not tested. https://gist.github.com/pelex/873cabcf69b8cedf21551867becfa12d

**Comment by dandrits** [comment]
@pelex ok thx a lot I 'll check it and give it a try and I ll give you some feedback

**Comment by dandrits** [comment]
Thank you all for the help but I moved to zend autodiscover for wsdl generation.

**Comment by dandrits** [comment]
In case someone has the same problem with me adding soap auth header to autogenerated wsdl is able by CWsdlGenerator of Yii cheers!

**Comment by piotrooo** [comment]
Now is possible to set a header parameter. Check annotation `@WebParam` with a header property.
