### ISSUE TITLE
Quick start ? 

### ISSUE THREAD

**Issue by yoyoy** [piotrooo/wsdl-creator#45]
Hello, i'm verry sorry but, I've installed the package via composer from here
https://packagist.org/packages/piotrooo/wsdl-creator

and now I would like to try o generate a wsdl from my class file ... 
i've tested to changed included class in examples\document_literal\service.php 
but nothing change in the generated wsdl ...

I'm sorry but is it possible to have a quick start example ? which I can use with my own class ? 

thanks a lot

**Comment by piotrooo** [comment]
Hello,
sure I give you an example.

Look at class located at `tests/Fixtures/ServiceAllAnnotations.php`. This class describe some WS. 
To generate WSDL from this class annotations you should use:

```
print_r(WSDL::fromAnnotations(\Fixtures\ServiceAllAnnotations::class)->create());
```

And that's all. 

All things are clear now?
